import streamlit as st
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

# Title and introductory text
st.title('Stock Market Prediction Application')
st.write('This application predicts stock market trends using historical data and machine learning.')

# User input for stock selection
ticker = st.text_input('Enter the stock ticker symbol, e.g., AAPL, GOOGL, MSFT:', 'AAPL')
data = yf.download(ticker, start='2010-01-01', end='2023-01-01')

# Displaying the data as a dataframe
st.write('Displaying stock data:')
st.dataframe(data.tail())

### About This Application
This application demonstrates a machine learning approach to predicting stock market trends. It uses historical stock price data to train a model that aims to predict future price movements. Users can select different stocks and model types to see how different scenarios might perform.

### Educational Purpose
This application is designed for educational purposes to help users understand how machine learning can be applied in financial contexts. It allows users to experiment with different stocks and indicators and see simulated outcomes based on historical data.

### Disclaimer
This application is not intended to provide financial advice. The predictions and strategies generated by this application are based on historical data and should not be taken as guidance for real-world trading. Stock market investments carry risk, and users should consult with professional financial advisors before making investment decisions.

